export function tabs() {
    const tab1 = document.getElementsByClassName('tab')[0];
    const tab2 = document.getElementsByClassName('tab')[1];
    const tab3 = document.getElementsByClassName('tab')[2];
    const tab4 = document.getElementsByClassName('tab')[3];
    const tab5 = document.getElementsByClassName('tab')[4];
    const tab6 = document.getElementsByClassName('tab')[5];
    const tab7 = document.getElementsByClassName('tab')[6];
    const tab8 = document.getElementsByClassName('tab')[7];
    const tab9 = document.getElementsByClassName('tab')[8];
    const url = new URLSearchParams(window.location.search);
    const session = url.get('session-id');
    const titlebox = document.getElementById('title')!;
    tab1.addEventListener('click', () => {
        location.href = `?session-id=${session}&tab=1`;
        titlebox.focus();
        tab1.style.borderColor = 'orange';
        tab2.style.borderColor = 'blueviolet';
        tab3.style.borderColor = 'blueviolet';
        tab4.style.borderColor = 'blueviolet';
        tab5.style.borderColor = 'blueviolet';
        tab6.style.borderColor = 'blueviolet';
        tab7.style.borderColor = 'blueviolet';
        tab8.style.borderColor = 'blueviolet';
        tab9.style.borderColor = 'blueviolet';
    });
    tab2.addEventListener('click', () => {
        location.href = `?session-id=${session}&tab=2`;
        titlebox.focus();
        tab2.style.borderColor = 'orange';
        tab1.style.borderColor = 'blueviolet';
        tab3.style.borderColor = 'blueviolet';
        tab4.style.borderColor = 'blueviolet';
        tab5.style.borderColor = 'blueviolet';
        tab6.style.borderColor = 'blueviolet';
        tab7.style.borderColor = 'blueviolet';
        tab8.style.borderColor = 'blueviolet';
        tab9.style.borderColor = 'blueviolet';
    });
    tab3.addEventListener('click', () => {
        location.href = `?session-id=${session}&tab=3`;
        titlebox.focus();
        tab3.style.borderColor = 'orange';
        tab1.style.borderColor = 'blueviolet';
        tab2.style.borderColor = 'blueviolet';
        tab4.style.borderColor = 'blueviolet';
        tab5.style.borderColor = 'blueviolet';
        tab6.style.borderColor = 'blueviolet';
        tab7.style.borderColor = 'blueviolet';
        tab8.style.borderColor = 'blueviolet';
        tab9.style.borderColor = 'blueviolet';
    });
    tab4.addEventListener('click', () => {
        location.href = `?session-id=${session}&tab=4`;
        titlebox.focus();
        tab4.style.borderColor = 'orange';
        tab1.style.borderColor = 'blueviolet';
        tab2.style.borderColor = 'blueviolet';
        tab3.style.borderColor = 'blueviolet';
        tab5.style.borderColor = 'blueviolet';
        tab6.style.borderColor = 'blueviolet';
        tab7.style.borderColor = 'blueviolet';
        tab8.style.borderColor = 'blueviolet';
        tab9.style.borderColor = 'blueviolet';
    });
    tab5.addEventListener('click', () => {
        location.href = `?session-id=${session}&tab=5`;
        titlebox.focus();
        tab5.style.borderColor = 'orange';
        tab1.style.borderColor = 'blueviolet';
        tab2.style.borderColor = 'blueviolet';
        tab3.style.borderColor = 'blueviolet';
        tab4.style.borderColor = 'blueviolet';
        tab6.style.borderColor = 'blueviolet';
        tab7.style.borderColor = 'blueviolet';
        tab8.style.borderColor = 'blueviolet';
        tab9.style.borderColor = 'blueviolet';
    });
    tab6.addEventListener('click', () => {
        location.href = `?session-id=${session}&tab=6`;
        titlebox.focus();
        tab6.style.borderColor = 'orange';
        tab1.style.borderColor = 'blueviolet';
        tab2.style.borderColor = 'blueviolet';
        tab3.style.borderColor = 'blueviolet';
        tab4.style.borderColor = 'blueviolet';
        tab5.style.borderColor = 'blueviolet';
        tab7.style.borderColor = 'blueviolet';
        tab8.style.borderColor = 'blueviolet';
        tab9.style.borderColor = 'blueviolet';
    });
    tab7.addEventListener('click', () => {
        location.href = `?session-id=${session}&tab=7`;
        titlebox.focus();
        tab7.style.borderColor = 'orange';
        tab1.style.borderColor = 'blueviolet';
        tab2.style.borderColor = 'blueviolet';
        tab3.style.borderColor = 'blueviolet';
        tab4.style.borderColor = 'blueviolet';
        tab5.style.borderColor = 'blueviolet';
        tab6.style.borderColor = 'blueviolet';
        tab8.style.borderColor = 'blueviolet';
        tab9.style.borderColor = 'blueviolet';
    });
    tab8.addEventListener('click', () => {
        location.href = `?session-id=${session}&tab=8`;
        titlebox.focus();
        tab8.style.borderColor = 'orange';
        tab1.style.borderColor = 'blueviolet';
        tab2.style.borderColor = 'blueviolet';
        tab3.style.borderColor = 'blueviolet';
        tab4.style.borderColor = 'blueviolet';
        tab5.style.borderColor = 'blueviolet';
        tab6.style.borderColor = 'blueviolet';
        tab7.style.borderColor = 'blueviolet';
        tab9.style.borderColor = 'blueviolet';
    });
    tab9.addEventListener('click', () => {
        location.href = `?session-id=${session}&tab=9`;
        titlebox.focus();
        tab9.style.borderColor = 'orange';
        tab1.style.borderColor = 'blueviolet';
        tab2.style.borderColor = 'blueviolet';
        tab3.style.borderColor = 'blueviolet';
        tab4.style.borderColor = 'blueviolet';
        tab5.style.borderColor = 'blueviolet';
        tab6.style.borderColor = 'blueviolet';
        tab7.style.borderColor = 'blueviolet';
        tab8.style.borderColor = 'blueviolet';
    });
}